inherit_gem:
  ws-style:
    - default.yml

AllCops:
  Exclude:
    - "spec/dummy/bin/**/*"
    - "spec/dummy/db/migrate/**/*"
    - "spec/dummy/db/schema.rb"
    - "spec/dummy/log/**/*"
    - "spec/dummy/tmp/**/*"
  TargetRubyVersion: 2.7
