inherit_gem:
  ws-style:
    - default.yml

AllCops:
  Exclude:
    - "spec/dummy/bin/**/*"
    - "spec/dummy/db/migrate/**/*"
    - "spec/dummy/db/schema.rb"
    - "spec/dummy/log/**/*"
    - "spec/dummy/tmp/**/*"
  TargetRubyVersion: 3.2

Rails/SkipsModelValidations:
  Enabled: false

Vendor/StrictDryStruct:
  Enabled: false
