---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: eventsimple
  description: Event Driven Toolkit for Rails
  tags:
    - ruby
spec:
  type: library
  lifecycle: production
  owner: engineering
