default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["DATABASE_USERNAME"] || "postgres" %>
  host: <%= ENV["DATABASE_HOST"] || "localhost" %>
  password: <%= ENV["DATABASE_PASSWORD"] || "" %>

development:
  <<: *default
  database: dummy_development

test:
  <<: *default
  database: dummy_test

production:
  <<: *default
  database: dummy_production
