common: &common
  app_name: 'app-service'
  app_role: 'worker'
  app_env: 'development'

  logstash:
    host: '<%= ENV["LOGSTASH_HOST"] || "localhost" %>'
    port: '<%= ENV["LOGSTASH_PORT"] || 5050 %>'
    type: '<%= ENV["LOGSTASH_TYPE"] || :udp %>'

  rack_timeout_seconds: '<%= ENV["RACK_TIMEOUT_SECONDS"] || "15" %>'

  rollbar:
    access_token: '<%= ENV["ROLLBAR_ACCESS_TOKEN"] || "7dca5b6ce4ef40c3a73a3da80c20a1f7" %>'

  api_access_id: '<%= ENV["API_ACCESS_ID"] || "ebf9d509-cd6c-4b6b-9071-d105b070f812" %>'
  api_secret_key: '<%= ENV["API_SECRET_KEY"] || "Sy+fJVVf/U0WWjkya2G8BVrKQsuy4klZSIbqrDglpxJ1bdQ0opqEcY21CCtziHvzg5i9FuBPNZg2WE0NLBqeKd4KJLnfzr2IW7Iu7AqcRuV3W2hlSd5q/Q==" %>'

  jwt_secret: '<%= ENV["JWT_SECRET"] || "ArLtq8TcEpf9ulBuR+MPfeUNcWJx1zlrCxRBs887GJoGeqEp/kvgIDLlNNKWeIaLnROt1R/1DCptHAkSXJ4OyBq/N2BfOWcB" %>'

  auth_service:
    base_url: '<%= ENV["AUTH_SERVICE_BASE_URL"] || "http://auth-service.staging.iad.wealthsimple.com" %>'

  datadog_apm:
    enabled: '<%= ENV["DATADOG_APM_ENABLED"] || "false" %>'
    default_service: '<%= ENV["DATADOG_APM_DEFAULT_SERVICE"] || ENV["APP_NAME"] || "my_app" %>'
    debug: '<%= ENV["DATADOG_APM_DEBUG"] || "false" %>'
    hostname: '<%= ENV["DATADOG_APM_HOST"] || "localhost" %>'
    port: '<%= ENV["DATADOG_APM_PORT"] || 8126 %>'

  aws:
    region: '<%= ENV["AWS_REGION"] || "us-east-1" %>'
    instance_profile_enabled: '<%= ENV["AWS_INSTANCE_PROFILE_ENABLED"] || "false" %>'
    access_key_id: '<%= ENV["AWS_ACCESS_KEY_ID"] || "" %>'
    secret_access_key: '<%= ENV["AWS_SECRET_ACCESS_KEY"] || "" %>'

  sidekiq:
    redis_url: '<%= ENV["SIDEKIQ_REDIS_URL"] || ENV["REDIS_URL"] || "redis://127.0.0.1:6379" %>'

development:
  secret_key_base: 599ad1f7124b4d6e85afb4b5532c0b3bec628783386213357e918cc69d5da6b72ebe0da8508aaa3b0754b9f6cca7c6f40196e74beb76d9b4559c531b5670bac20fcd27944fe13f46928defdb2115eb3f08b02deabc27085a90b31d892f80c8f73554748b6f2bef86225cb4144a8ef357590b324f5e4bf15f68a36df5433d5320
  <<: *common

test:
  secret_key_base: c80fb323fdb9f7ab7ae0e50958e2745bd78b961e75f7e111c6031131689ec48caceabe258c6e6c29f7de5190caf17631b81eecc3e4550a2b02ebf67b01a2be461a3a9d6462346bd6811cb6dc8b9ab1bbaece55651d02ef1a8b07b4cab876cb1bb081bc37c1576b05a7fb4c5706a73480cf2f33602d99c3a2b5d45c4425cb1582
  <<: *common

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  <<: *common





#
#common: &common
#  app_name: 'app-service'
#  app_role: 'worker'
#  app_env: 'development'
#
#  rollbar:
#    access_token: 'ROLLBAR_ACCESS_TOKEN'
#
#  datadog_apm:
#    enabled: '<%= ENV["DATADOG_APM_ENABLED"] || "false" %>'
#    default_service: '<%= ENV["DATADOG_APM_DEFAULT_SERVICE"] || ENV["APP_NAME"] || "missing-service-name" %>'
#    debug: '<%= ENV["DATADOG_APM_DEBUG"] || "false" %>'
#    hostname: '<%= ENV["DATADOG_APM_HOST"] || "localhost" %>'
#    port: '<%= ENV["DATADOG_APM_PORT"] || 8126 %>'
#
#  logstash:
#    host: '<%= ENV["LOGSTASH_HOST"] || "localhost" %>'
#    port: '<%= ENV["LOGSTASH_PORT"] || 5050 %>'
#    type: '<%= ENV["LOGSTASH_TYPE"] || :udp %>'
#
#development:
#  <<: *common
#
#test:
#  <<: *common
