---
name: Main
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
        env:
          BUNDLE_GEMS__CONTRIBSYS__COM: ${{ secrets.BUNDLE_GEMS__CONTRIBSYS__COM }}
          BUNDLE_NEXUS__IAD__W10EXTERNAL__COM: ${{ secrets.BUNDLE_NEXUS__IAD__W10EXTERNAL__COM }}
      - name: Fetch main branch
        run: git fetch origin main
      - name: Lint
        uses: wealthsimple/toolbox-script@v1
        with:
          script: await toolbox.ruby.lint.run();
      - name: Run database container
        run: |
          docker run \
            --detach \
            --name eventable_postgresql \
            -e POSTGRES_HOST_AUTH_METHOD=trust \
            -p 5432:5432 \
            --health-cmd pg_isready \
            --health-interval 10s \
            --health-timeout 5s \
            --health-retries 5 \
            postgres:13.4-alpine \
            postgres -c 'max_connections=300'
      - name: Setup databases
        run: bundle exec rake db:setup
      - name: Test
        uses: wealthsimple/toolbox-script@v1
        with:
          script: await toolbox.ruby.test.run();
      - name: Release
        uses: wealthsimple/toolbox-script@v1
        with:
          script: await toolbox.ruby.publish.run();
          nexus_gem_credentials_file: ${{ secrets.NEXUS_GEM_CREDENTIALS_FILE }}
